project:
  type: website
  output-dir: docs
  resources:
    - "*.png"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    grid:
      body-width: 800px
      margin-width: 0px
    toc-location: left
    toc-title: "Índice"
