project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    background: white
    position: fixed

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left
    toc-title: "Índice"
